name: 'Test Build'

on: push

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Set up JDK 1.8'
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: 'Checkout submodules'
        uses: textbook/git-checkout-submodule-action@master
      - name: 'Install 32-bit dependencies'
        run: sudo apt-get install -y libc6-i386 lib32z1 lib32stdc++6
      - name: 'Make Auth Key'
        run: ant MakeAuthKey
        working-directory: appinventor
      - name: 'Build AppyBuilder'
        run: ant noplay
        working-directory: appinventor
      - name: 'Build Companion'
        run: ant
        working-directory: appinventor
      - name: 'Upload Companion to Artifacts'
        uses: actions/upload-artifact@v1.0.0
        with:
          name: AppyBuilder Gold
          path: appinventor/build/buildserver/AppyBuilder Gold.apk
      - name: 'Run Tests'
        run: ant tests
        working-directory: appinventor
      - name: 'Upload Test Reports to Artifacts'
        uses: actions/upload-artifact@v1.0.0
        with:
          name: Test Reports
          path: appinventor/reports
      - name: 'War Zip'
        uses: actions/upload-artifact@v1.0.0
        with:
          name: Pack War
          path: appinventor/appengine/build/war
      - name: 'BuildServer Tar'
        run: ant BuildDeploymentTar
        working-directory: appinventor/buildserver
      - name: 'Pack BuildServer'
        uses: actions/upload-artifact@v1.0.0
        with:
          name: Pack War
          path: appinventor/build/buildserver/BuildServer.tar
